pipeline:
  setup:
    image: node:11
    when:
      event: [push]
    commands:
      - yarn
  integration-tests:
    image: circleci/node:11-browsers
    when:
      event: [push]
    group: testing
    commands:
      # This image runs with a custom user by default
      # Has to be root to gain access to
      - sudo su -c "yarn protractor:ci"
  lint:
    image: node:11
    when:
      event: [push]
    group: testing
    commands:
      - yarn lint
  test:
    image: node:11
    when:
      event: [push]
    group: testing
    commands:
      - MONGO_URL=mongodb://mongodb:27017/vote-test yarn mocha
  build:
    image: node:11
    when:
      event: [push]
      branch:
        exclude: [prod]
    group: testing
    commands:
      - yarn build
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    repo: abakus/vote
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

services:
  mongodb:
    image: mongo:3.6
