pipeline:
  setup:
    image: node:11
    when:
      event: [push, pull_request]
    commands:
      - yarn
  integration-tests:
    image: node:11
    when:
      event: [push]
    group: testing
    secrets:
      - sauce_access_key
      - sauce_username
    commands:
      - wget https://saucelabs.com/downloads/sc-4.4.11-linux.tar.gz
      - tar -xzf sc-4.4.11-linux.tar.gz
      - cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --readyfile ~/sauce_is_ready &
      - while [ ! -e ~/sauce_is_ready ]; do sleep 0.5; echo -n "."; done
      - yarn protractor
  lint:
    image: node:11
    when:
      event: [push, pull_request]
    group: testing
    commands:
      - yarn lint
  test:
    image: node:11
    when:
      event: [push, pull_request]
    group: testing
    commands:
      - MONGO_URL=mongodb://mongodb:27017/vote-test yarn mocha
  build:
    image: node:11
    when:
      event: [push, pull_request]
      branch:
        exclude: [prod]
    group: testing
    commands:
      - yarn build
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
      status: success
    repo: abakus/vote
    secrets: [docker_username, docker_password]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

services:
  mongodb:
    image: mongo:3.6
